version: "3.9"

services:
  engine:
    depends_on:
      - database
      - kafka
    build: ./engine/
    container_name: engine
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - zbdihd

  golang-measurement-generator:
    depends_on:
      - kafka
    build: ./golang-measurement-generator/
    container_name: golang-measurement-generator
    ports:
      - "8085:8085"
    env_file:
      - .env
    networks:
      - zbdihd

  database:
    image: 'bitnami/postgresql:16.0.0'
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=user
      - POSTGRESQL_REPLICATION_PASSWORD=password
      - POSTGRESQL_PASSWORD=password
    networks:
      - zbdihd

  database-replica:
    image: 'bitnami/postgresql:16.0.0'
    container_name: database-replica
    ports:
      - "5433:5432"
    depends_on:
      - database
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=database
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=user
      - POSTGRESQL_REPLICATION_PASSWORD=password
      - POSTGRESQL_PASSWORD=password
    networks:
      - zbdihd

  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    env_file:
      - .env
    networks:
      - zbdihd

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    env_file:
      - .env
    depends_on:
      - zookeeper
    networks:
      - zbdihd
  pmm-monitoring:
    container_name: pmm-monitoring
    image: 'percona/pmm-server:2.41.2'
    ports:
      - '443:443'
    networks:
      - zbdihd

volumes:
  zbdihd:

networks:
  zbdihd:
    driver: bridge
