version: "3.9"

services:
  engine:
    depends_on:
      - database
      - kafka
    build: ./engine/
    container_name: engine
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - hdised

  golang-measurement-generator:
    depends_on:
      - kafka
    build: ./golang-measurement-generator/
    container_name: golang-measurement-generator
    ports:
      - "8085:8085"
    env_file:
      - .env
    networks:
      - hdised

  database:
    build: ./postgres-config/
    container_name: database
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - hdised
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    env_file:
      - .env
    networks:
      - hdised

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    env_file:
      - .env
    depends_on:
      - zookeeper
    networks:
      - hdised

  pmm-monitoring:
    container_name: pmm-monitoring
    image: 'percona/pmm-server:2.41.2'
    ports:
      - '443:443'
    networks:
      - hdised

volumes:
  hdised:

networks:
  hdised:
    driver: bridge
