version: "3.9"

services:
  engine:
    depends_on:
      - database
      - kafka
    build: ./engine/
    container_name: engine
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - hdised

  golang-measurement-generator:
    depends_on:
      - kafka
    build: ./golang-measurement-generator/
    container_name: golang-measurement-generator
    ports:
      - "8085:8080"
    env_file:
      - .env
    networks:
      - hdised

  database:
    container_name: database
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - hdised

  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    env_file:
      - .env
    networks:
      - hdised

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    env_file:
      - .env
    depends_on:
      - zookeeper
    networks:
      - hdised

volumes:
  hdised:

networks:
  hdised:
    driver: bridge
